services:
  tests:
    image: buildkite/plugin-tester
    platform: linux/amd64
    volumes:
      - ".:/plugin"
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'Sage/sbc-shared']
    volumes:
      - ".:/plugin:ro"
