services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    image: sbc-shared-buildkite-plugin-tester
    platform: linux/amd64
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
    volumes:
      - ".:/plugin"
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'Sage/sbc-shared']
    volumes:
      - ".:/plugin:ro"
