name: SBC Shared Build Tools
description: Common functions to used to build and deliver SBC docker images
author: https://github.com/Sage
requirements:
  - aws
configuration:
  properties:
    action:
      type: string
    environment:
      type: string
    landscape:
      type: string
    tag:
      type: string
    target_tag:
      type: string
    repo_prefix:
      type: string
    region:
      type: string
    gem_host:
      type: string
    db_image:
      type: boolean
    push_test_image:
      type: boolean
  required:
    - action
  additionalProperties: false
