name: SBC Shared Build Tools
description: Common functions to used to build and deliver SBC docker images
author: https://github.com/Sage
requirements:
  - aws
configuration:
  properties:
    action:
      type: string
    environment:
      type: string
    landscape:
      type: string
    tag:
      type: string
    repo_prefix:
      type: string
  required:
    - action
    - environment
    - landscape
    - account_id
  additionalProperties: false